steps:
  - id: 'build-image'
    name: 'gcr.io/cloud-builders/docker'
    args:
      - build
      - -t
      - gcr.io/bux-assignment-jleon/assignment-repo/what-time-is-it:$COMMIT_SHA
      - .

  - id: 'push-image'
    name: gcr.io/cloud_builders/docker
    args:
      - push
      - gcr.io/bux-assignment-jleon/assignment-repo/what-time-is-it:$COMMIT_SHA

  - id: 'setup-kubectl'
    name: gcr.io/cloud-builders/kubectl
    args:
      - cluster-info
    env:
      - CLOUDSDK_COMPUTE_REGION=us-east1
      - CLOUDSDK_CONTAINER_CLUSTER=bux-assignment-jleon-gke

  - id: 'deploy-chart'
    name: 'alpine/helm:3.5.3'
    args:
      - 'upgrade'
      - 'what-time-is-it'
      - '-i'
      - '--namespace'
      - 'default'
      - '-f'
      - 'chart/values.yaml'
      - '--set'
      - 'image.tag=$COMMIT_SHA'
      - 'chart'
      