apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: GitRepository
metadata:
  name: what-time-is-it
  namespace: time
spec:
  interval: 1m
  url: https://github.com/alexacid88/bux-assignment.git
  ref:
    branch: master
  ignore: |
    # include charts directory
    !/chart