apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: what-time-is-it
  namespace: time
spec:
  interval: 5m
  upgrade: 
    force: true
  chart:
    spec:
      chart: ./chart
      version: '>=0.0.1'
      sourceRef:
        kind: GitRepository
        name: what-time-is-it
        namespace: time
  values:
    replicaCount: 2