apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: what-time-is-it
  namespace: default
spec:
  interval: 5m
  upgrade: 
    preserveValues: true
    cleanupOnFail: true
  chart:
    spec:
      chart: ./chart
      version: '>=0.0.1'
      sourceRef:
        kind: GitRepository
        name: what-time-is-it
        namespace: flux-system
  values:
    replicaCount: 2