apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: what-time-is-it
  namespace: default
spec:
  interval: 5m
  chart:
    spec:
      chart: ./chart
      version: '0.1.0'
      sourceRef:
        kind: GitRepository
        name: what-time-is-it
        namespace: flux-system
      interval: 1m
  values:
    replicaCount: 2